---
title: Helen Tran; Designer
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
exclude:
- README.md
- config.rb
- sass
name: Helen Tran; Product Designer
description: Helen Tran is a Product Designer. She blogs about her life, technology,
  management and design.
url: http://helentran.com
plugins:
- jekyll-feed
- jekyll-redirect-from
permalink: "/:title"
future: true